parameters:
- name: activateVersion
  displayName: Select Activate Version
  type: string
  default: KB
  values:
    - KB
    - BB

- name: SourceRepo
  displayName: Enter full UNC FQDN Path of the x64/86 MSI (DO NOT ADD trailing "\" eg. \\kbshares.corp.bank.nzpfs.co.nz\releases\_Drop\Activate)
  type: string
  default:

stages:
# Upload MSI
  - template: Template-PublishArtifact.yml
    parameters:
      stageName: 'Upload_MSI'
      stageDisplayName: 'Upload MSI'
      SourceRepo: ${{parameters.SourceRepo}}
      envName: 'PRD-WLG'
      condition: succeeded()
  
#Create Application to deploy to MECM
  - task: powershell@2
    condition: eq(${{parameters.dryRun}}, False)
    name: createApplicationFor${{parameters.taskGroupName}}
    displayName: Create MECM Application to Deploy
    inputs:
      targetType: filePath
      filePath: ${{parameters.scriptsFolder}}\CreateMECMApplicationToDeploy.ps1
      arguments: '-packageName InTouch-Client-${{parameters.releaseTo}}-${{parameters.revisionVersion}} -releaseTo ${{parameters.releaseTo}} -softwareVersion ${{parameters.revisionVersion}} -SCCMsiteServer ${{parameters.mecmSiteServer}} -applicationFolderPath "${{parameters.applicationFolderPath}}" -msiFolderLocation "${{parameters.msiFolderLocation}}" -contentDistributionPoints "${{parameters.contentDistributionPoints}}"'
      
# Release to PVT Users
  - template: ReleaseEnvironmentTemplate.yml
      parameters:
      stageName: 'Citrix_Activate_DeployandSeal'
      stageDisplayName: 'Citrix Activate Deploy and Seal'
      activateVersion: ${{parameters.activateVersion}}   
      appEnvironment: ${{parameters.appEnvironment}}
      envName: ${{variables.envName}}
      condition: succeeded()

  # Release to  Activate KB
   - template: ReleaseEnvironmentTemplate.yml
      parameters:
      stageName: 'Citrix_Activate_DeployandSeal'
      stageDisplayName: 'Citrix Activate Deploy and Seal'
      activateVersion: ${{parameters.activateVersion}}   
      appEnvironment: ${{parameters.appEnvironment}}
      envName: ${{variables.envName}}
      condition: succeeded()

 # Release to  All Users
   - template: ReleaseEnvironmentTemplate.yml
      parameters:
      stageName: 'Citrix_Activate_DeployandSeal'
      stageDisplayName: 'Citrix Activate Deploy and Seal'
      activateVersion: ${{parameters.activateVersion}}   
      appEnvironment: ${{parameters.appEnvironment}}
      envName: ${{variables.envName}}
      condition: succeeded()
      
  #Clean Up Previous Versions
