trigger: none
pr: none

# SIT-only pipeline using Activate-SIT library values

parameters:
  - name: revisionVersion
    type: string

  - name: releaseTo
    type: string
    default: 'KB'
    values: ['KB','BB']

  # Folder on the agent containing your product sources (for sourceFolder below)
  - name: workspace
    type: string
    default: '$(Build.SourcesDirectory)'

variables:
  # Imports from Library → Activate-SIT:
  # MECM_ApplicationFolderpath = Application\Workstation\Pipeline
  # MECM_MsiFolderLocation     = \\kbcfgmgresource\apps$\Workstation\Pipeline
  # MECM_PreProdSiteServer     = kbstcfgmgr005.corp.bank.sit.kiwibank.internal
  # MECM_PVTCollection         = Activate KB/BB PVT SIT
  # MECM_ScheduledCacheTime    = Now
  # MECM_ScheduledInstallTime  = Now
  # MECM_SITContentDistributionPoints = Kiwibank All Distribution Points
  # MECM_SITLimitingCollectionName    = All Desktop and Server Clients
  # MECM_SITSoftwareCentreCollection  = All Users
  - group: Activate-SIT

  # Map parameter to classic variable expected by templates
  - name: revisionVersion
    value: ${{ parameters.revisionVersion }}

  - name: vmImage
    value: 'windows-2022'

stages:
  # 0) Bootstrap: copy PS scripts to a predictable folder for templates (scriptsFolder)
  - stage: Bootstrap_Scripts
    displayName: 'Bootstrap scripts'
    jobs:
      - job: Copy
        pool: { vmImage: $(vmImage) }
        steps:
          - powershell: |
              New-Item -ItemType Directory -Path "$(Pipeline.Workspace)\Cache" -Force | Out-Null
              Copy-Item "$(Build.SourcesDirectory)\scripts\*.ps1" "$(Pipeline.Workspace)\Cache" -Force
            displayName: 'Copy PS scripts to $(Pipeline.Workspace)\Cache'

  # 1) Create/brand/distribute the application (SIT)
  - template: ../templates/MECMApplicationTemplate.yml
    parameters:
      dryRun: False
      taskGroupName: "Scheduled${{parameters.releaseTo}}"
      revisionVersion: $(revisionVersion)
      releaseTo: ${{parameters.releaseTo}}
      sourceFolder: ${{ parameters.workspace }}\InTouch Client
      scriptsFolder: $(Pipeline.Workspace)\Cache
      mecmSiteServer: $(MECM_PreProdSiteServer)
      msiFolderLocation: $(MECM_MsiFolderLocation)
      applicationFolderPath: $(MECM_ApplicationFolderpath)
      contentDistributionPoints: $(MECM_SITContentDistributionPoints)

  # 2) Make application Available to PVT users (SIT Software Center visibility for PVT ring)
  - template: ../templates/MECMAvailableDeploymentTemplate.yml
    parameters:
      dryRun: False
      taskGroupName: "PVT${{parameters.releaseTo}}"
      revisionVersion: $(revisionVersion)
      releaseTo: ${{parameters.releaseTo}}
      scriptsFolder: $(Pipeline.Workspace)\Cache
      mecmSiteServer: $(MECM_PreProdSiteServer)
      limitingCollectionName: $(MECM_SITLimitingCollectionName)
      userCollectionName: $(MECM_PVTCollection)            # Activate KB/BB PVT SIT
      scheduledInstallTime: $(MECM_ScheduledCacheTime)     # "Now" per Library
      refreshDeviceCollection: false                       # user collection → no device refresh

  # 3) Make application Required for SIT groups (scheduled install)
  - template: ../templates/MECMRequiredDeploymentTemplate.yml
    parameters:
      dryRun: False
      taskGroupName: "Scheduled${{parameters.releaseTo}}"
      revisionVersion: $(revisionVersion)
      releaseTo: ${{parameters.releaseTo}}
      scriptsFolder: $(Pipeline.Workspace)\Cache
      mecmSiteServer: $(MECM_PreProdSiteServer)
      limitingCollectionName: $(MECM_SITLimitingCollectionName)
      userCollectionName: $(MECM_SITSoftwareCentreCollection)  # "All Users" per Library
      scheduledCacheTime: $(MECM_ScheduledCacheTime)           # "Now" per Library
      scheduledInstallTime: $(MECM_ScheduledInstallTime)       # "Now" per Library
