parameters:
  dryRun: False
  revisionVersion: ''
  releaseTo: ''         # KB or BB
  releaseRing: 'PROD'
  scriptsFolder: ''
  mecmSiteServer: ''
  mecmSiteCode: ''
  applicationFolderPath: ''
  iconRepo: ''
  iconFileName: ''
  contentDistributionPoints: ''   # "Corp;VPN"

stages:
- stage: Create_MECM_App
  displayName: 'Create MECM Application'
  dependsOn: Upload_MSI
  jobs:
  - job: CreateApp
    pool: { vmImage: 'windows-2022' }
    steps:
    - download: current
      artifact: drop
      displayName: 'Download MSI artifact'
    - task: PowerShell@2
      name: createApp
      displayName: 'Create & distribute MECM application'
      inputs:
        targetType: filePath
        filePath: ${{ parameters.scriptsFolder }}\CreateMECMApplicationToDeploy.ps1
        arguments: >
          -DryRun:(${ if eq(parameters.dryRun, True) }$true${ else }$false${ end })
          -ReleaseTo '${{ parameters.releaseTo }}'
          -SoftwareVersion '${{ parameters.revisionVersion }}'
          -ReleaseRing '${{ parameters.releaseRing }}'
          -SCCMSiteServer '${{ parameters.mecmSiteServer }}'
          -SCCMSiteCode '${{ parameters.mecmSiteCode }}'
          -ApplicationFolderPath '${{ parameters.applicationFolderPath }}'
          -MsiFolderLocation "$(Pipeline.Workspace)\drop"
          -IconRepo '${{ parameters.iconRepo }}'
          -IconFileName '${{ parameters.iconFileName }}'
          -ContentDistributionPoints '${{ parameters.contentDistributionPoints }}'
