parameters:
    stageName: '--'
    stageDisplayName: ''
    SourceRepo: ''
    envName: '--'

stages:
  - stage: ${{parameters.stageName}}
    displayName: ${{parameters.stageDisplayName}}
    jobs:
    - deployment: 'Upload_MSI_as_artifact'
      displayName: 'Upload MSI as artifact'
      environment: 
          name: ${{parameters.envName}}
          resourceType: VirtualMachine
          tags: "citrix-activate-artifact-upload"
      workspace:
          clean: all  
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: ${{parameters.SourceRepo}}
                artifactName: 'installer'
