parameters:
  scriptsFolder: ''          # e.g., $(Pipeline.Workspace)\Cache
  sourceRepo: ''             # UNC root with MSI(s)
  msiFileName: ''            # optional exact MSI name
  preferArch: 'any'          # 'x86' | 'x64' | 'any'
  msiPattern: 'Activate.*\.msi'
  artifactName: 'drop'

stages:
- stage: Upload_MSI
  displayName: 'Upload MSI'
  dependsOn: Bootstrap_Scripts
  jobs:
  - job: CopyPublish
    pool: { vmImage: 'windows-2022' }
    steps:
    - task: PowerShell@2
      name: upload
      displayName: 'Select & copy MSI from UNC'
      inputs:
        targetType: filePath
        filePath: ${{ parameters.scriptsFolder }}\UploadMSI.ps1
        arguments: >
          -SourceRepo '${{ parameters.sourceRepo }}'
          -OutputDir '$(Build.SourcesDirectory)\${{ parameters.artifactName }}'
          -MsiFileName '${{ parameters.msiFileName }}'
          -MsiPattern '${{ parameters.msiPattern }}'
          -PreferArch '${{ parameters.preferArch }}'
    - publish: '$(Build.SourcesDirectory)/${{ parameters.artifactName }}'
      artifact: ${{ parameters.artifactName }}
      displayName: 'Publish MSI artifact'
